### ISSUE TITLE
Does not work on OS X 10.10.4 w/PyCharm 4.5.3

### ISSUE THREAD

**Issue by gamename** [fioan89/sourcesync#22] opened 2015-07-30 16:57 UTC
Hi,

After installing the plugin, I get this when PyCharm restarts:
11:48:58 PluginException: cannot create class "org.wavescale.sourcesync.action.ActionLocalFileToRemote" [Plugin: org.wavescale.sourcesync]
11:48:59 Platform and Plugin Updates: The following plugin is ready to update: Settings Repository
11:49:06 PluginException: cannot create class "org.wavescale.sourcesync.action.ActionProjectConnectionConfig" [Plugin: org.wavescale.sourcesync]
11:49:23 PluginException: cannot create class "org.wavescale.sourcesync.action.ActionSourceSyncMenu" [Plugin: org.wavescale.sourcesync]

Here is the idea.log:
https://gist.github.com/gamename/adf278b79d5820b106a9

Thanks,
-T

**Comment by fioan89** [comment] 2015-07-31 07:05
Hi,

It's pretty hard to debug this kind of issues without proper hardware and software. I don't have access to an Apple device - but I gave a quick look at the log and I think these two lines are the issue:
* Caused by: com.intellij.diagnostic.PluginException: org/wavescale/sourcesync/action/ActionLocalFileToRemote : Unsupported major.minor version 51.0 [Plugin: org.wavescale.sourcesync]
* 2015-07-30 11:48:50,336 [   4644]  ERROR - nsions.impl.ExtensionPointImpl - JDK: 1.6.0_65 

The first line tells that the Java Runtime used by PyCharm does not support class with version number 51.0 (i.e classes compiled with JDK 1.7)
The second line tells me that you are using the JDK 1.6. You should also know that Source Sync is compiled and supports only version >= JDK 1.7. So the issue here is your jdk version which is lower. 

This is not only an issue for Source Sync. I can see that other plugins you have installed - some related  to docker are having the same issues:
* 2015-07-30 09:44:46,826 [   5174]  ERROR - nsions.impl.ExtensionPointImpl - com/intellij/docker/DockerCloudType : Unsupported major.minor version 51.0 [Plugin: Docker] 
* Caused by: com.intellij.diagnostic.PluginException: com/intellij/docker/action/StartContainerAction : Unsupported major.minor version 51.0 [Plugin: Docker]

So I'm recommending an upgrade to at least java 7, though java 8 is already released so you might as well upgrade to that version if your are already going with the upgrade from JDK 1.6.

The JDK you have most probably comes with your Apple OS X - and probably Apple has a different timeline support for Java 6. But Oracle (from which I get the JDK for my box) ended the public support for JDK 1.6 somewhere around 2013:
http://www.oracle.com/technetwork/java/eol-135779.html

Please upgrade the JDK and ping me so that I can close this issue. Here is a link to JDK 8 from Oracle: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
After install you might have to update some java paths like JAVA_HOME.

Regards,
Ioan

**Comment by fioan89** [comment] 2015-08-05 06:18
Hi, 
Can I close this issue? Did you fixed the error?

Cheers,
Ioan

**Comment by gamename** [comment] 2015-08-05 13:49
Hi Guy,

Yes! That fixed it.  Thanks for the reminder. Yes, please close it.

-T

**Closed** 2015-08-05 13:55 UTC
