### ISSUE TITLE
java.lang.NullPointerException while uploading using FTPS

### ISSUE THREAD

**Issue by yanivyam** [fioan89/sourcesync#37] opened 2016-08-20 17:01 UTC
Hi,

I am getting the exception below while uploading using FTPS:
OS: Mac OS
IDE: PyCharm 2016.1

null
java.lang.NullPointerException
    at org.wavescale.sourcesync.synchronizer.FTPSFileSynchronizer.syncFile(FTPSFileSynchronizer.java:123)
    at org.wavescale.sourcesync.action.ActionSelectedFilesToRemote$1.run(ActionSelectedFilesToRemote.java:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by fioan89** [comment] 2016-11-17 07:46
Uhm, can you provide the source sync version? Is anything logged on the Event Log tab from PyCharm (according to the code it should)

Looking at the latest source code version and comparing with the stack trace it seems that plugin could not open a file handler on the server in order to write the synced file.

**Comment by fioan89** [comment] 2017-01-04 15:23
I'm going to close this due to insufficient information. I can't reproduce the issue with the latest plugin and a basic configuration.  Please feel free to reopen it if you encounter the problem again.

**Closed by fioan89** 2017-01-04 15:23 UTC
