### ISSUE TITLE
"sourcesync connection configuration" window opened in background

### ISSUE THREAD

**Issue by thorstenkampe** [fioan89/sourcesync#11] opened 2015-01-31 11:59 UTC
PyCharm 4.0.4 on Windows: Tools > Source Sync results in the *sourcesync connection configuration* window opened in the background. There is no visual feedback that something happened or opened.

**Comment by leonard84** [comment] 2015-06-11 15:38
Also happens with Intellij 14.1.3 on Windows7

**Comment by dlech** [comment] 2016-02-22 20:37
Ditto on PyCharm 5.0.4 on OS X 10.11.3

**Comment by dlech** [comment] 2016-02-22 20:47
This bug was fixed by <https://github.com/fioan89/sourcesync/commit/f3c2b46210dfb874cdf0b552648e972e86fc7fe8>. However, that commit also introduces a new similar bug that when you click the `+` button in the connection configuration window, a new dialog opens behind the connection configuration window and the connection configuration window has to be moved out of the way to see the new dialog because the connection configuration window is now set to always on top.

**Comment by fioan89** [comment] 2016-02-22 20:50
Do you guys have a second monitor attached? I can't reproduce it on a Linux machine. I would take a look on a windows machine and see how it's going.

**Comment by dlech** [comment] 2016-02-22 20:52
No second monitor. I'm on OS X 10.11.3.

**Comment by dlech** [comment] 2016-02-22 20:56
I just tried on Linux too and it is OK, so OS X must handle "always on top" differently.

**Comment by fioan89** [comment] 2016-05-01 22:38
This issue should be fixed with 7bf6e3a. Changed the configuration window from a frame to a dialog. Also it's childs will be dialogs, so the order of visibility should be now: IDE -> Source Sync Configuration Window -> The "Add target" window, the latter having the focus.

Also now the Configuration window and the "Add target" is centered on the parent when they are set to visible state.

**Comment by fioan89** [comment] 2016-05-07 17:13
Fixed with 1.9 release.

**Closed by fioan89** 2016-05-07 17:13 UTC
